name: Publish

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install & Build
      run: |
        mkdir public
        cd ./modules/guard-cli
        npm ci
        npm run build
      env:
        CI: true

    - name: Generate AllowList
      run: |
        node ./modules/guard-cli/dist/main.js generate \
        --name AdGuard-Home-List.Allow.txt \
        --badge badge-allow.json \
        --external ./allowlist/external \
        --custom ./allowlist/custom \
        --concatExternal ./allowlist/concat \
        --convertToAllow \
        --output ./public

    - name: Generate BlockList
      run: |
        node ./modules/guard-cli/dist/main.js generate \
        --name AdGuard-Home-List.Block.txt \
        --badge badge-block.json \
        --external ./blocklist/external \
        --custom ./blocklist/custom \
        --concatExternal ./blocklist/concat \
        --output ./public

    - name: Create or Update Release and Upload Files
      uses: ncipollo/release-action@v1
      with:
        artifacts: "public/AdGuard-Home-List.Allow.txt,public/AdGuard-Home-List.Block.txt,public/badge-allow.json,public/badge-block.json"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "latest"
        name: "Latest Build"
        body: "Latest Build of ${{ github.event_name }}"
        allowUpdates: true
        removeArtifacts: true
        replacesArtifacts: true
